name: Galactifun
version: '${version}'
main: io.github.addoncommunity.galactifun.Galactifun
api-version: '1.21.11'
description: Galactifun Legacy - space, planets, rockets and astronomy for Slimefun Legacy
authors: [Seggan, Mooy1, GallowsDove, ProfElements, Charmandiox9]
contributors: [wickidcow]
depend:
  - Slimefun
softdepend:
  - BentoBox
  - Multiverse-Core
  - Multiverse-Inventories
  - Multiverse-Portals
  - Geyser-Spigot
  - floodgate

commands:
  galactifun:
    description: Galactifun main command
    usage: /galactifun <subcommand>
    aliases: [gf, galactic]
