name: Galactifun
version: '${version}'
main: io.github.addoncommunity.galactifun.Galactifun
api-version: '26.2'
description: Space exploration, planetary worlds, rockets, life support, alien ecosystems, and astronomy for Slimefun Legacy.
authors: [Seggan, Mooy1, GallowsDove, ProfElements, Charmandiox9]
contributors: [wickidcow]
website: https://github.com/wickidcow/SF_Galactifun
depend:
  - Slimefun
softdepend:
  - BentoBox
loadbefore:
  - Multiverse-Core

commands:
  galactifun:
    description: Galactifun main command
    usage: /galactifun <subcommand>
    aliases: [gf, galactic]
